# Generated by Django 5.2.11 on 2026-03-02 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=50)),
                ('base_rent', models.IntegerField()),
                ('hp_modifier', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_code', models.CharField(choices=[('110105', '朝阳区某传媒高校 (CUC)'), ('110108', '海淀区某顶级学府 (PKU)')], max_length=6)),
                ('money', models.FloatField(default=5000.0)),
                ('hp', models.IntegerField(default=100)),
                ('san', models.IntegerField(default=100)),
                ('thesis_progress', models.FloatField(default=0.0)),
                ('current_month', models.DateField()),
                ('is_dorm_cleared', models.BooleanField(default=False)),
                ('is_graduated', models.BooleanField(default=False)),
                ('current_district', models.CharField(blank=True, max_length=20, null=True)),
                ('rent_contract_end', models.DateField(blank=True, null=True)),
                ('monthly_allowance', models.FloatField(default=1000.0)),
                ('is_game_over', models.BooleanField(default=False)),
                ('ending_type', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
