# Generated by Django 5.2.11 on 2026-03-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='souvenirs_owned',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='hp',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='player',
            name='san',
            field=models.FloatField(default=100.0),
        ),
    ]
