# Generated by Django 5.2.11 on 2026-03-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_souvenirs_owned_alter_player_hp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='san_cap',
            field=models.IntegerField(default=100),
        ),
    ]
