# Generated by Django 5.2.11 on 2026-03-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_san_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='has_moved_this_month',
            field=models.BooleanField(default=False),
        ),
    ]
