# Generated by Django 5.2.11 on 2026-03-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_player_has_moved_this_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='deposit_held',
            field=models.FloatField(default=0.0),
        ),
    ]
