# Generated by Django 5.2.11 on 2026-03-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_player_deposit_held'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='next_month_san_cap',
            field=models.IntegerField(default=100),
        ),
    ]
