# Generated by Django 5.2.11 on 2026-03-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_player_next_month_san_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_in_renewal_crisis',
            field=models.BooleanField(default=False),
        ),
    ]
