# Generated by Django 4.2.29 on 2026-03-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_player_is_in_renewal_crisis'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='has_research_fund',
            field=models.BooleanField(default=False),
        ),
    ]
