# Generated by Django 4.2.29 on 2026-03-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_player_has_research_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cuc_completion_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='pku_completion_count',
            field=models.IntegerField(default=0),
        ),
    ]
