# Generated by Django 5.2.11 on 2026-04-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_player_cuc_completion_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='action_history',
            field=models.TextField(blank=True, default=''),
        ),
    ]
