# Generated by Django 4.2.29 on 2026-06-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_player_action_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='dorm_eviction_forced_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='dorm_eviction_phase_1_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='dorm_eviction_phase_2_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='dorm_eviction_phase_3_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='gpu_mining_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='hp_max',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='player',
            name='mining_detection_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
