# Generated by Django 4.2.29 on 2026-06-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_player_dorm_eviction_forced_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='temp_housing_active',
            field=models.BooleanField(default=False),
        ),
    ]
