# Generated by Django 4.2.29 on 2026-06-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_player_temp_housing_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='dorm_eviction_delayed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='dorm_eviction_denial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='dorm_eviction_ignored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='dorm_eviction_prep_start',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='dorm_eviction_rented',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='dorm_eviction_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='dorm_eviction_tried_beg',
            field=models.BooleanField(default=False),
        ),
    ]
